Fix NoClassDefFoundError
This fixes the noclassdef found error as the JBTableHintProvider was
removed in IDEA 2016.1.  This replaces it with the ui.JBTable class
and it seems to work as expected.